# Only used locally
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: portfolio_local
      POSTGRES_PASSWORD: password
    ports:
      - "5442:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
